apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc #pvc name
spec:
  accessModes:
  - ReadWriteOnce # Only one node per time can read and write
  resources:
    requests:
      storage: 2Mi # Storage size requested